from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "output/pdf/tarzan_packcell_embodiment_rfq_v1.pdf"

def footer(canvas, doc):
    canvas.saveState(); canvas.setFillColor(colors.white); canvas.rect(0, 0, A4[0], A4[1], fill=1, stroke=0)
    canvas.setFont("Helvetica", 8); canvas.setFillColor(colors.HexColor("#607080"))
    canvas.drawString(18*mm, 10*mm, "Tarzan PackCell - Confidential application engineering packet")
    canvas.drawRightString(192*mm, 10*mm, f"Page {doc.page}"); canvas.restoreState()

def bullets(items, style):
    return [Paragraph("• " + item, style) for item in items]

def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    styles = getSampleStyleSheet(); navy=colors.HexColor("#123247"); blue=colors.HexColor("#1675A9"); pale=colors.HexColor("#EAF3F7")
    title=ParagraphStyle("Title2", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=25, leading=29, textColor=navy, alignment=TA_CENTER, spaceAfter=8)
    h1=ParagraphStyle("H1x", parent=styles["Heading1"], fontName="Helvetica-Bold", fontSize=15, leading=18, textColor=navy, spaceBefore=10, spaceAfter=7)
    h2=ParagraphStyle("H2x", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=11, leading=14, textColor=blue, spaceBefore=7, spaceAfter=4)
    body=ParagraphStyle("Bodyx", parent=styles["BodyText"], fontSize=9.4, leading=13, textColor=colors.HexColor("#24323A"), spaceAfter=5)
    small=ParagraphStyle("Smallx", parent=body, fontSize=8.2, leading=10.5)
    doc=SimpleDocTemplate(str(OUT), pagesize=A4, leftMargin=18*mm, rightMargin=18*mm, topMargin=17*mm, bottomMargin=17*mm, title="Tarzan PackCell Embodiment RFQ v1")
    story=[Spacer(1,18*mm),Paragraph("TARZAN PACKCELL",title),Paragraph("Embodiment RFQ & Application Engineering Packet v1",ParagraphStyle("Sub",parent=title,fontSize=15,leading=19,textColor=blue)),Spacer(1,8*mm),Paragraph("Teach once. Execute on changed orders.",ParagraphStyle("Tag",parent=body,fontSize=13,leading=17,alignment=TA_CENTER,textColor=navy)),Spacer(1,12*mm)]
    box=Table([[Paragraph("REQUEST",small),Paragraph("Written validation of a commercially defensible single-arm, jaw/suction packing embodiment.",body)], [Paragraph("FROZEN GATES",small),Paragraph("106 mm minimum usable jaw opening; 8 kg workpiece; 20% arm payload margin; 3 mm insertion clearance.",body)], [Paragraph("CURRENT RESULT",small),Paragraph("No eligible arm-tool pair is frozen. UR15 is the conditional reach/payload preference; tooling remains unresolved.",body)]],colWidths=[35*mm,130*mm])
    box.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),pale),("BOX",(0,0),(-1,-1),.8,blue),("INNERGRID",(0,0),(-1,-1),.3,colors.white),("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),7),("RIGHTPADDING",(0,0),(-1,-1),7),("TOPPADDING",(0,0),(-1,-1),7),("BOTTOMPADDING",(0,0),(-1,-1),7)]));story += [box,Spacer(1,10*mm),Paragraph("Purpose",h1),Paragraph("Tarzan is selecting a single-arm embodiment for a teach-once small-sortable ecommerce packing cell. This packet requests manufacturer and integrator application engineering. It is not a purchase order and does not relax the frozen task envelope.",body),Spacer(1,18*mm),Paragraph("12 July 2026 | Tarzan Engineering",ParagraphStyle("Date",parent=body,alignment=TA_CENTER,textColor=colors.HexColor("#607080"))),PageBreak()]
    story += [Paragraph("1. Frozen task envelope",h1)]
    data=[["Parameter","Requirement"],["Development layouts","50 deterministic layouts; confirmation layouts sealed"],["Maximum reach proxy","1.148 m including current tool-length assumption"],["Carton interior","400 x 300 x 250 mm"],["Representative objects","50 x 50 x 50; 120 x 80 x 60; 250 x 150 x 100 mm"],["Maximum workpiece","8.0 kg"],["Jaw opening","106 mm minimum; 110-120 mm preferred"],["Payload margin","20% on tool plus workpiece"],["Workpiece CoG offset","Up to 200 mm in current selection model"],["Current static moment proxy","23.1 Nm before custom-finger mass and acceleration"],["Insertion clearance","3 mm minimum"],["Object force limit","80 N unless metadata explicitly permits more"]]
    t=Table([[Paragraph(str(c),small) for c in row] for row in data],colWidths=[55*mm,110*mm],repeatRows=1);t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),navy),("TEXTCOLOR",(0,0),(-1,0),colors.white),("GRID",(0,0),(-1,-1),.35,colors.HexColor("#B8C8D0")),("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white,pale]),("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),6),("RIGHTPADDING",(0,0),(-1,-1),6),("TOPPADDING",(0,0),(-1,-1),5),("BOTTOMPADDING",(0,0),(-1,-1),5)]));story += [t,Spacer(1,6*mm),Paragraph("Provisional performance target",h2),Paragraph("Quote against 1.5 m/s2 nominal acceleration, 2.0 m/s2 peak, and 12 seconds per item. These are commercial targets for application review, not validated robot limits. Return a manufacturer-supported acceleration and cycle estimate.",body),Paragraph("Current reach proxy",h2)]
    reach=Table([["Arm","Max required","Min margin","Derated mass","Status"],["UR15","1.148 m","152 mm","11.4 kg","Conditional preference"],["UR20","1.148 m","602 mm","11.4 kg","Use only if required"]],colWidths=[25*mm,32*mm,30*mm,30*mm,48*mm]);reach.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),blue),("TEXTCOLOR",(0,0),(-1,0),colors.white),("GRID",(0,0),(-1,-1),.35,colors.HexColor("#B8C8D0")),("ALIGN",(1,1),(-2,-1),"CENTER"),("FONTSIZE",(0,0),(-1,-1),8.5),("TOPPADDING",(0,0),(-1,-1),5),("BOTTOMPADDING",(0,0),(-1,-1),5)]));story += [reach,PageBreak()]
    story += [Paragraph("2. Arm application questions",h1)] + bullets(["Confirm payload and CoG validity for tool plus 8 kg workpiece with 20% margin.","Confirm wrist force/torque validity at maximum extension and declared CoG.","Provide acceleration, speed, orientation, and stopping-distance derating.","Identify unreachable, singular, collision-limited, or reduced-performance poses.","Estimate cycle time and state whether UR20 materially improves the application.","Describe force/torque, safety, service, and controls integration.","Provide CAD, kinematic, inertial, collision, payload-curve, and interface data."],body)
    story += [Paragraph("3. End-effector application questions",h1),Paragraph("Custom-finger OnRobot 2FG14",h2),Paragraph("The standard 105 mm external opening does not pass. Propose a manufacturer-supported configuration providing at least 106 mm, preferably 110-120 mm, and validate:",body)] + bullets(["Minimum closure for 30-50 mm objects.","Finger dimensions, mass, CoG, inertia, bending moment, and permitted materials.","Force transmission and allowable acceleration with an 8 kg workpiece.","Compliance with documented 25 Nm Y and 30 Nm X platform limits.","Controllable force range for fragile packaged goods.","Carton-entry and box-rim collision envelope.","CAD, inertial, collision, controls, revision, and licensing data."],body)
    story += [Paragraph("Hybrid jaws and suction",h2),Paragraph("Identify a supported vacuum or hybrid architecture for flat sealed cardboard/plastic parcels up to 8 kg. Provide cup geometry, required seal area, porosity limits, vacuum reserve, acceleration derating, tool mass/CoG, seal-loss diagnostics, tool-change time, and safe recovery. Unknown surfaces must fall back to jaws or human handling.",body),PageBreak()]
    story += [Paragraph("4. Required simulation and integration data",h1)] + bullets(["Official CAD with revision identifiers and licensing terms.","URDF or equivalent kinematic description where available.","Link/tool masses, centers of gravity, and inertias.","Collision geometry distinct from visual geometry.","Joint, actuator, force, speed, acceleration, and payload limits.","TCP/contact frames and finger or suction contact geometry.","Control protocol documentation and integration examples.","Permission for internal simulation, derived MJCF generation, and benchmark publication."],body)
    story += [Paragraph("5. Requested written outcome",h1),Paragraph("Return one of the following, with every boundary condition stated:",body)] + bullets(["UR15 valid across the declared envelope.","UR20 required, with the precise disqualifying UR15 condition.","Custom 2FG14 valid, with a reviewed finger design.","Hybrid jaw/suction architecture required.","No supported configuration."],body)
    story += [Spacer(1,5*mm),Paragraph("Tarzan will not relax the 106 mm or 8 kg gates to fit a preferred component. Unsupported items must be escalated rather than attempted.",ParagraphStyle("Callout",parent=body,fontName="Helvetica-Bold",textColor=navy,borderColor=blue,borderWidth=.8,borderPadding=8,backColor=pale)),Spacer(1,10*mm),Paragraph("Attachments available",h2)] + bullets(["Full 50-layout waypoint artifact.","Coupled embodiment decision matrix.","Hybrid portfolio specification.","Light-sortable MVP specification.","Panda negative embodiment evidence and anti-cheat boundary."],body)
    doc.build(story,onFirstPage=footer,onLaterPages=footer);print(OUT)

if __name__ == "__main__": main()
